version: 2
updates:

  - package-ecosystem: gitsubmodule
    commit-message:
      prefix: "chore"
    directory: /
    schedule:
      interval: monthly
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"

  - package-ecosystem: docker
    commit-message:
      prefix: "chore"
    directory: /tests/integration
    schedule:
      interval: monthly
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"
