stages:
  - test
  - renovate

include:
  - project: Northern.tech/Mender/mendertesting
    file:
      - qa-common/runner.yml
      - qa-common/retry.yml
  - project: 'Northern.tech/Mender/mendertesting'
    file:
      - '.gitlab-ci-github-status-updates.yml'
      - '.gitlab-ci-check-license.yml'
      - '.gitlab-ci-check-python3-format.yml'
  - component: gitlab.com/Northern.tech/Mender/mendertesting/commit-lint@master
  - component: gitlab.com/renovate-bot/renovate-runner/renovate.gitlab-ci@main


default:
  tags: !reference [.qa-common-default-runner, tags]
  retry: !reference [.qa-common-default-retry, retry]

variables:
  MENDER_VERSION: mender-master
  MENDER_ARTIFACT_VERSION: 4.1.0
  MENDER_CONFIGURE_VERSION: $CI_COMMIT_REF_NAME

  # Renovate required variables
  RENOVATE_PLATFORM: github
  RENOVATE_ENDPOINT: "https://api.github.com"
  RENOVATE_GIT_AUTHOR: "mender-test-bot <mender@northern.tech>"
  RENOVATE_TOKEN: $GITHUB_BOT_TOKEN_REPO_FULL
  RENOVATE_GITHUB_COM_TOKEN: $GITHUB_BOT_TOKEN_REPO_FULL
  RENOVATE_REPOSITORIES: "mendersoftware/$CI_PROJECT_NAME"
  RENOVATE_REQUIRE_CONFIG: "optional"
  RENOVATE_ONBOARDING: "false"
  RENOVATE_GIT_PRIVATE_KEY: $SSH_PRIVATE_KEY
  RENOVATE_CONFIG_FILE: "$CI_PROJECT_DIR/renovate.json"
  FORCE_RENOVATE_RUN:
    description: "Force a renovate bot run"
    value: "false"
    options:
      - "true"
      - "false"

# Override rules
renovate:
  needs: []
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web" && $FORCE_RENOVATE_RUN == "true"'
  stage: renovate
  tags:
    - k8s-small

test:unit:
  stage: test
  needs: []
  image: python:alpine
  before_script:
    - apk add --update git make curl
    - git submodule update --init --recursive
  script:
    - make test

test:integration:
  stage: test
  needs: []
  image: docker:24.0.7-dind-alpine3.18
  tags:
    - hetzner-amd-beefy
  before_script:
    # DinD setup in Mender CI runners
    - unset DOCKER_HOST
    - unset DOCKER_TLS_VERIFY
    - unset DOCKER_CERT_PATH
    # Start dockerd in the background
    - /usr/local/bin/dockerd &
    # Wait for dockerd to start
    - |-
      MAX_WAIT=30
      while [ ! -e "/var/run/docker.sock" ] && [ $MAX_WAIT -gt 0 ]; do
        MAX_WAIT=$(($MAX_WAIT - 1))
        sleep 1
      done
    # Verify that the docker server is up and running
    - docker version
    # Init the git submodules
    - apk add --update --no-cache $(cat tests/integration/apk-requirements.txt)
    - git submodule update --init --recursive
    # Install test dependencies
    - apk add --update --no-cache $(cat tests/integration/mender_integration/tests/requirements-system/apk-requirements.txt)
    - pip install -r tests/integration/mender_integration/tests/requirements-python/python-requirements.txt
    # Download and install mender-artifact
    - apk add --no-cache dpkg
    - wget "https://downloads.mender.io/repos/workstation-tools/pool/main/m/mender-artifact/mender-artifact_${MENDER_ARTIFACT_VERSION}-1%2bubuntu%2bnoble_amd64.deb"
      --output-document mender-artifact.deb
    - dpkg --extract mender-artifact.deb /
  script:
    - cd tests/integration/
    - GENERATE_PYTEST_REPORT=true ./run.sh
  artifacts:
    expire_in: 2w
    when: always
    reports:
      junit: ${CI_PROJECT_DIR}/tests/integration/report.xml
