# Copyright 2026 Northern.tech AS
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

import sys
from os import path

sys.path.insert(0, path.abspath(path.dirname(__file__)))

backend_tests_path = path.abspath(
    path.join(path.dirname(__file__), "..", "mender_server", "backend", "tests")
)
sys.path.insert(0, backend_tests_path)

import logging
from contextlib import contextmanager

import filelock
import pytest
import urllib3

import helpers
import setup
from server import wait_for_backend_ready
from setup import SERVER_PROJECTS, project_name_client

from server import Server
from setup import Env, clients_up, wait_for_devices

from mender_test_containers.conftest import *
from mender_test_containers.container_props import *

logging.getLogger("requests").setLevel(logging.CRITICAL)
logging.getLogger("paramiko").setLevel(logging.CRITICAL)
logging.getLogger("urllib3").setLevel(logging.CRITICAL)
logging.getLogger("filelock").setLevel(logging.INFO)
logging.getLogger("invoke").setLevel(logging.INFO)

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger()
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

machine_name = "qemux86-64"
collect_ignore = ["mender_server"]
inline_logs = False

# The compose files are generated by run.sh next to the ones they are derived from, so they have to
# be run from within the submodule.
SERVER_DIR = "mender_server"
OS_COMPOSE_FILES = ["docker-compose.testing.yml"]
ENTERPRISE_COMPOSE_FILES = [
    "docker-compose.testing.yml",
    "docker-compose.testing.enterprise.yml",
]

CLIENT_COMPOSE_FILE = "docker-compose.client.rofs.configure.yml"


@contextmanager
def _shared_backend(worker_id, tmp_path_factory, plan, files):
    """Start the backend for one flavour once per session, however many xdist workers there are.

    Session fixtures run once per worker, so both ends need cross-process coordination: the first
    worker in starts the backend, every worker waits until it is usable, and only the last worker
    out tears it down. Tearing down per worker would pull the backend out from under the workers
    that are still running tests, since xdist hands out tests dynamically.

    The lock and the refcount are per flavour, and each flavour has its own compose project, so a
    session mixing OS and enterprise tests runs both backends side by side rather than one of them
    silently attaching to the other's stack.
    """
    project = SERVER_PROJECTS[plan]

    if worker_id == "master":
        # Not running under xdist, so no other worker can be sharing the backend.
        helpers.docker_compose_start(project_name=project, files=files, cwd=SERVER_DIR)
        try:
            wait_for_backend_ready(project)
            yield
        finally:
            helpers.docker_compose_stop(
                project_name=project, files=files, cwd=SERVER_DIR
            )
        return

    # getbasetemp() is per worker, its parent is shared by all workers of this run.
    shared_dir = tmp_path_factory.getbasetemp().parent
    lock = filelock.FileLock(str(shared_dir / f"backend-{plan}.lock"))
    refcount = shared_dir / f"backend-{plan}.refcount"

    with lock:
        workers = int(refcount.read_text()) if refcount.exists() else 0
        if workers == 0:
            helpers.docker_compose_start(
                project_name=project, files=files, cwd=SERVER_DIR
            )
        refcount.write_text(str(workers + 1))

    try:
        # Outside the lock, so workers wait concurrently rather than one after another.
        wait_for_backend_ready(project)
        yield
    finally:
        with lock:
            workers = int(refcount.read_text()) - 1
            refcount.write_text(str(workers))
            if workers == 0:
                helpers.docker_compose_stop(
                    project_name=project, files=files, cwd=SERVER_DIR
                )


@pytest.fixture(scope="session")
def os_backend_server(worker_id, tmp_path_factory):
    with _shared_backend(worker_id, tmp_path_factory, "os", OS_COMPOSE_FILES):
        yield


@pytest.fixture(scope="session")
def enterprise_backend_server(worker_id, tmp_path_factory):
    with _shared_backend(
        worker_id, tmp_path_factory, "enterprise", ENTERPRISE_COMPOSE_FILES
    ):
        yield


@pytest.fixture(scope="function", autouse=True)
def devices_down():
    yield
    # The client compose file declares the backend network as external, so teardown has to resolve
    # it to the same name clients_up used.
    helpers.docker_compose_stop(
        project_name=project_name_client,
        files=[CLIENT_COMPOSE_FILE],
        env=setup.client_compose_env(),
    )


# -------------------------------------------------------------------------

MenderTestQemux86_64RofsMenderConfigure = ContainerProps(
    image_name="mendersoftware/mender-client-qemu-rofs-mender-configure",
    append_mender_version=False,
    key_filename=path.join(
        path.dirname(path.realpath(__file__)),
        "../mender_test_containers/qemu-test-containers/ssh-keys/key",
    ),
)

TEST_CONTAINER_LIST = [MenderTestQemux86_64RofsMenderConfigure]


@pytest.fixture(scope="session", params=TEST_CONTAINER_LIST)
def setup_test_container_props(request):
    return request.param


@pytest.fixture(scope="session")
def mender_version():
    return "master"


@pytest.fixture(scope="function")
def standard_setup_one_rofs_configure_client(request, os_backend_server):
    env = Env()
    server = Server()
    env.server = server

    env.devices = clients_up(1, CLIENT_COMPOSE_FILE, network=server.network)
    env.device = env.devices[0]

    wait_for_devices(env)

    server.accept_devices(env.devices)
    assert 1 == len(server.get_accepted_devices())

    return env
