# Copyright 2026 Northern.tech AS
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

import os
import time
import logging
import subprocess

from helpers import docker_lock
from testutils.infra.device import MenderDevice

logger = logging.getLogger(__name__)

# One compose project per backend flavour, so a session containing both OS and enterprise tests can
# run both backends side by side. The testing compose files generated by run.sh publish no host
# ports, so the two stacks do not collide.
#
# Defined in server.py, which is kept identical across the client repos; re-exported here because
# that is where callers have always imported it from.
from server import SERVER_PROJECTS, server_project, server_network  # noqa: F401

# One client compose project per process, so that the autouse teardown of one xdist worker cannot
# take down another worker's device. Derived from the worker id rather than randomised, so it cannot
# collide. run.sh removes leftover virtual_device* containers before each run.
project_name_client = "virtual_device" + os.environ.get(
    "PYTEST_XDIST_WORKER", str(os.getpid())
)

# Remembered from clients_up so that teardown resolves the same external network the clients were
# created with. Per process, so xdist workers cannot clobber each other's value.
client_network = None


def client_compose_env():
    return {"MENDER_SERVER_NETWORK": client_network or server_network("os")}


class Env:
    def __init__(self):
        self.server = None
        self.devices = []
        self.device = None
        self.gateway = None
        self.auth = None

    def get_virtual_network_host_ip(self):
        container = f"{project_name_client}-mender-client-1"
        cmd = [
            "docker",
            "inspect",
            "-f",
            "{{range .NetworkSettings.Networks}}{{.Gateway}}{{end}}",
            container,
        ]
        with docker_lock:
            output = subprocess.check_output(cmd)
        return output.decode().strip()


def clients_up(number_of_clients, compose_file, tenant_token=None, network=None):
    global client_network
    client_network = network or server_network("os")

    with docker_lock:
        cmd = [
            "docker",
            "compose",
            "-p",
            project_name_client,
            "-f",
            compose_file,
            "up",
            "-d",
            "--scale",
            f"mender-client={number_of_clients}",
        ]

        env = os.environ.copy()
        # Which backend the device talks to, so clients can be pointed at either flavour.
        env["MENDER_SERVER_NETWORK"] = client_network
        if tenant_token:
            env["TENANT_TOKEN"] = tenant_token

        subprocess.check_call(cmd, env=env)

        clients = []
        for device_number in range(1, number_of_clients + 1):
            device = f"{project_name_client}-mender-client-{device_number}"
            client_ip = subprocess.check_output(
                [
                    "docker",
                    "inspect",
                    "-f",
                    "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}",
                    device,
                ],
                text=True,
            ).strip()
            clients.append(MenderDevice(f"{client_ip}:8822"))

    return clients


def clients_down(compose_file):
    with docker_lock:
        cmd = [
            "docker",
            "compose",
            "-p",
            project_name_client,
            "-f",
            compose_file,
            "down",
            "-v",
            "--remove-orphans",
        ]
        subprocess.run(cmd, check=False, env={**os.environ, **client_compose_env()})


def wait_for_devices(env):
    # Give the device some time to start so we don't get
    # stuck in a 60 second ssh exception right away
    time.sleep(15)
    for device in env.devices:
        logger.info(f"Waiting for '{device.host}'")
        device.ssh_is_opened()
