#!/bin/sh
# Copyright 2021 Northern.tech AS
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

set -e

CONFIG=${TEST_CONFIG:-/var/lib/mender-configure/device-config.json}
APPLY_CMD=${TEST_APPLY_CMD:-/usr/lib/mender-configure/apply-device-config}

STATE="$1"
FILES="$2"

BACKUP="$FILES/tmp/device-config-backup.json"

safe_copy() {
    if [ -n "$3" ]; then
        echo "safe_copy can only handle one file copy at a time" 1>&2
        exit 2
    fi
    cp "$1" "$2".tmp
    sync "$2".tmp
    mv "$2".tmp "$2"
    sync "$(dirname "$2")"
}

case "$STATE" in

    SupportsRollback)
        echo "Yes"
        ;;

    ArtifactInstall)
        if [ -e "$CONFIG" ]; then
            safe_copy "$CONFIG" "$BACKUP"
        fi
        safe_copy "$FILES/header/meta-data" "$CONFIG"
        RET=0
        "$APPLY_CMD" "$CONFIG" || RET=$?
        if [ $RET -eq 20 ]; then
            touch "$FILES/tmp/needs-reboot"
            sync "$FILES/tmp/needs-reboot"
            sync "$FILES/tmp"
            exit 0
        else
            exit $RET
        fi
        ;;

    NeedsArtifactReboot)
        if [ -e "$FILES/tmp/needs-reboot" ]; then
            echo "Automatic"
        else
            echo "No"
        fi
        ;;

    ArtifactRollback)
        if ! [ -e "$BACKUP" ]; then
            # Either there was no preexisting configuration, or the update was
            # interrupted before we could make a backup: Nothing to do.
            exit 0
        fi
        safe_copy "$BACKUP" "$CONFIG"
        RET=0
        "$APPLY_CMD" "$CONFIG" || RET=$?
        if [ $RET -eq 20 ]; then
            touch "$FILES/tmp/needs-reboot"
            sync "$FILES/tmp/needs-reboot"
            sync "$FILES/tmp"
            exit 0
        else
            exit $RET
        fi
        ;;

esac

exit 0

